groups:
  - name: wasm-wizard-alerts
    rules:
      # High error rate alert
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} over the last 5 minutes"

      # High response time alert
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s over the last 5 minutes"

      # WASM execution timeout alert
      - alert: WasmExecutionTimeout
        expr: increase(wasm_execution_timeouts_total[5m]) > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "WASM execution timeouts detected"
          description: "{{ $value }} WASM executions timed out in the last 5 minutes"

      # High memory usage alert
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 512
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Process is using {{ $value }}MB of memory"

      # Database connection failures
      - alert: DatabaseConnectionFailure
        expr: increase(database_connection_errors_total[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection failures"
          description: "{{ $value }} database connection failures in the last 5 minutes"

      # Rate limit exceeded frequently
      - alert: HighRateLimitHits
        expr: rate(rate_limit_exceeded_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High rate limit hits"
          description: "Rate limits are being exceeded {{ $value }} times per second"

      # Service down alert
      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Wasm Wizard service is down"
          description: "Wasm Wizard service has been down for more than 30 seconds"
