apiVersion: v1
kind: Namespace
metadata:
  name: wasm-wizard-staging
  labels:
    environment: staging
    app: wasm-wizard

---
apiVersion: v1
kind: Namespace
metadata:
  name: wasm-wizard-production
  labels:
    environment: production
    app: wasm-wizard

---
# Staging Secrets Template
apiVersion: v1
kind: Secret
metadata:
  name: wasm-wizard-secrets
  namespace: wasm-wizard-staging
  labels:
    app: wasm-wizard
    environment: staging
type: Opaque
data:
  # Base64 encoded values - replace with actual values during deployment
  database-url: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQGxvY2FsaG9zdDo1NDMyL2RiX25hbWU= # postgres://user:password@localhost:5432/db_name
  redis-url: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ== # redis://localhost:6379
  api-salt: c3RhZ2luZ19hcGlfc2FsdF9jaGFuZ2VfbWU= # staging_api_salt_change_me
  jwt-secret: c3RhZ2luZ19qd3Rfc2VjcmV0X2NoYW5nZV9tZQ== # staging_jwt_secret_change_me

---
# Production Secrets Template
apiVersion: v1
kind: Secret
metadata:
  name: wasm-wizard-secrets
  namespace: wasm-wizard-production
  labels:
    app: wasm-wizard
    environment: production
type: Opaque
data:
  # Base64 encoded values - replace with actual values during deployment
  database-url: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQGxvY2FsaG9zdDo1NDMyL2RiX25hbWU= # postgres://user:password@localhost:5432/db_name
  redis-url: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ== # redis://localhost:6379
  api-salt: cHJvZHVjdGlvbl9hcGlfc2FsdF9jaGFuZ2VfbWU= # production_api_salt_change_me
  jwt-secret: cHJvZHVjdGlvbl9qd3Rfc2VjcmV0X2NoYW5nZV9tZQ== # production_jwt_secret_change_me

---
# Network Policies for Production
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wasm-wizard-production-network-policy
  namespace: wasm-wizard-production
spec:
  podSelector:
    matchLabels:
      app: wasm-wizard
      environment: production
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          app: prometheus
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 6379  # Redis
    - protocol: TCP
      port: 53    # DNS
    - protocol: UDP
      port: 53    # DNS
    - protocol: TCP
      port: 443   # HTTPS
