name: Manual Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        type: choice
        options:
        - staging
        - production
      version:
        description: 'Version/commit to rollback to'
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rollback deployment
        run: |
          echo "Rolling back ${{ github.event.inputs.environment }} to version ${{ github.event.inputs.version }}"
          # Add your rollback logic here, e.g. kubectl rollout undo or helm rollback
          # Example:
          # kubectl rollout undo deployment/wasmwiz -n wasmwiz-${{ github.event.inputs.environment }} --to-revision=${{ github.event.inputs.version }}

      - name: Notify Slack
        if: env.SLACK_WEBHOOK != ''
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Rollback to ${{ github.event.inputs.version }} in ${{ github.event.inputs.environment }} triggered by ${{ github.actor }}."}' $SLACK_WEBHOOK